export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_WEBSOCKET = 'SET_WEBSOCKET';
export const SET_CLIENT_NAME = 'SET_CLIENT_NAME';
export const SET_LOGIN_HANDLER = 'SET_LOGIN_HANDLER';
export const SET_LOGOUT_HANDLER = 'SET_LOGOUT_HANDLER';
